In [1]:
import pandas as pd
import numpy as np

In [2]:
dfFinal = pd.read_csv(r'DATOS/dfFinal.csv')
ratings = pd.read_csv(r'DATOS/ratings.csv')

In [3]:
#CUENTO LAS FILAS DEL CSV RAITINGS
num_filas = ratings.shape[0]
print("El dataframe tiene", num_filas, "filas.")

El dataframe tiene 9524289 filas.

In [4]:
#BORRO FILAS DUPLICADAS YA QUE TENGO LOS PROMEDIOS
ratings = ratings.drop_duplicates(subset=['id'])

In [5]:
#UNO EL ARCHIVO CON EL DF FINAL
dfUnido1 = pd.merge(dfFinal, ratings, on='id')

In [7]:
#LO MUESTRO
dfUnido1

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0_x,show_id,type,title,director,cast,country,date_added,...,description,id,platforma,duration_int,duration_type,Unnamed: 0_y,userId,rating_y,timestamp,rating_prom
0,0,0,0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,...,a small fishing village must procure a local d...,ns1,amazon,113.0,min,2407110,64,4.5,1085081152,3.580275
1,14191,14191,14191,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,...,a small fishing village must procure a local d...,ns1,amazon,113.0,min,2407110,64,4.5,1085081152,3.580275
2,1,1,1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,...,a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min,6721003,332,4.0,1341586517,3.545000
3,14192,14192,14192,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,...,a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min,6721003,332,4.0,1341586517,3.545000
4,2,2,2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,...,after a man discovers his wife is cheating on ...,ns3,amazon,74.0,min,8330867,492,4.0,1280504676,3.584123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22132,14186,14186,14186,s3069,tv show,star trek: the original series,NaN,NaN,united states,NaN,...,the 23rd century adventures of captain james t...,hs3069,hulu,NaN,NaN,1752121,47,4.0,1036709506,3.495475
22133,14187,14187,14187,s3070,tv show,star trek: voyager,NaN,NaN,united states,NaN,...,catapulted into the distant sector of the gala...,hs3070,hulu,NaN,NaN,7867154,434,2.5,1165619011,3.485075
22134,14188,14188,14188,s3071,tv show,the fades,NaN,NaN,united kingdom,NaN,...,seventeen-year-old paul is haunted by apocalyp...,hs3071,hulu,NaN,NaN,542170,19,2.5,1321323206,3.540302
22135,14189,14189,14189,s3072,tv show,the twilight zone,NaN,NaN,united states,NaN,...,rod serling's seminal anthology series focused...,hs3072,hulu,NaN,NaN,6258858,294,2.5,1165196264,3.506667
22136,14190,14190,14190,s3073,tv show,tokyo magnitude 8.0,NaN,NaN,japan,NaN,...,the devastation is unleashed in the span of se...,hs3073,hulu,NaN,NaN,8927811,681,4.0,835889856,3.600462

In [8]:
num_filas = ratings.shape[0]
print("El dataframe tiene", num_filas, "filas.")

El dataframe tiene 22998 filas.

In [9]:
dfFinal

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,id,platforma,duration_int,duration_type
0,0,0,0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,ns1,amazon,113.0,min
1,1,1,1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min
2,2,2,2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,ns3,amazon,74.0,min
3,3,3,3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",ns4,amazon,69.0,min
4,4,4,4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,ns5,amazon,45.0,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23854,23854,23854,23854,s9664,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",NaN,NaN,1940,7+,60 min,comedy,new york city street principles get an east si...,ns9664,amazon,60.0,min
23855,23855,23855,23855,s9665,tv show,planet patrol,NaN,"dick vosburgh, ronnie stevens, libby morris, m...",NaN,NaN,2018,13+,4 seasons,tv shows,"this is earth, 2100ad - and these are the adve...",ns9665,amazon,NaN,NaN
23856,23856,23856,23856,s9666,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",NaN,NaN,2008,r,90 min,action,"in war-torn eastern europe, a world-weary grou...",ns9666,amazon,90.0,min
23857,23857,23857,23857,s9667,tv show,maradona: blessed dream,NaN,"esteban recagno, ezequiel stremiz, luciano vit...",NaN,NaN,2021,tv-ma,1 season,"drama, sports","the series tells the story of diego maradona, ...",ns9667,amazon,NaN,NaN
23858,23858,23858,23858,s9668,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",NaN,NaN,2010,r,103 min,"action, drama, suspense","harry brown, starring two-time academy award w...",ns9668,amazon,103.0,min

DROPEO COLUMNAS INNECESARIAS

In [10]:
dfUnido1 = dfUnido1.drop(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0_x'], axis=1)

In [12]:
dfFinal = dfFinal.drop(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0'], axis=1)

In [18]:
dfUnido1

,show_id,type,title,director,cast,country,date_added,release_year,rating_x,duration,listed_in,description,id,platforma,duration_int,duration_type,timestamp,rating_prom
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,ns1,amazon,113.0,min,1085081152,3.580275
1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,ns1,amazon,113.0,min,1085081152,3.580275
2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min,1341586517,3.545000
3,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min,1341586517,3.545000
4,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,ns3,amazon,74.0,min,1280504676,3.584123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22132,s3069,tv show,star trek: the original series,NaN,NaN,united states,NaN,1966,tv-pg,3 seasons,"action, adventure, classics",the 23rd century adventures of captain james t...,hs3069,hulu,NaN,NaN,1036709506,3.495475
22133,s3070,tv show,star trek: voyager,NaN,NaN,united states,NaN,1997,tv-pg,7 seasons,"action, adventure, science fiction",catapulted into the distant sector of the gala...,hs3070,hulu,NaN,NaN,1165619011,3.485075
22134,s3071,tv show,the fades,NaN,NaN,united kingdom,NaN,2011,tv-14,1 season,"horror, international, science fiction",seventeen-year-old paul is haunted by apocalyp...,hs3071,hulu,NaN,NaN,1321323206,3.540302
22135,s3072,tv show,the twilight zone,NaN,NaN,united states,NaN,1959,tv-pg,5 seasons,"classics, science fiction, thriller",rod serling's seminal anthology series focused...,hs3072,hulu,NaN,NaN,1165196264,3.506667
22136,s3073,tv show,tokyo magnitude 8.0,NaN,NaN,japan,NaN,2009,tv-14,1 season,"anime, drama, international",the devastation is unleashed in the span of se...,hs3073,hulu,NaN,NaN,835889856,3.600462

In [14]:
dfFinal.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,id,platforma,duration_int,duration_type
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,ns1,amazon,113.0,min
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,ns3,amazon,74.0,min
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",ns4,amazon,69.0,min
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,ns5,amazon,45.0,min

In [16]:
dfUnido1 = dfUnido1.drop(['rating_y','userId','Unnamed: 0_y'], axis=1)

In [17]:
dfUnido1

,show_id,type,title,director,cast,country,date_added,release_year,rating_x,duration,listed_in,description,id,platforma,duration_int,duration_type,timestamp,rating_prom
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,ns1,amazon,113.0,min,1085081152,3.580275
1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,ns1,amazon,113.0,min,1085081152,3.580275
2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min,1341586517,3.545000
3,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,ns2,amazon,110.0,min,1341586517,3.545000
4,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,ns3,amazon,74.0,min,1280504676,3.584123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22132,s3069,tv show,star trek: the original series,NaN,NaN,united states,NaN,1966,tv-pg,3 seasons,"action, adventure, classics",the 23rd century adventures of captain james t...,hs3069,hulu,NaN,NaN,1036709506,3.495475
22133,s3070,tv show,star trek: voyager,NaN,NaN,united states,NaN,1997,tv-pg,7 seasons,"action, adventure, science fiction",catapulted into the distant sector of the gala...,hs3070,hulu,NaN,NaN,1165619011,3.485075
22134,s3071,tv show,the fades,NaN,NaN,united kingdom,NaN,2011,tv-14,1 season,"horror, international, science fiction",seventeen-year-old paul is haunted by apocalyp...,hs3071,hulu,NaN,NaN,1321323206,3.540302
22135,s3072,tv show,the twilight zone,NaN,NaN,united states,NaN,1959,tv-pg,5 seasons,"classics, science fiction, thriller",rod serling's seminal anthology series focused...,hs3072,hulu,NaN,NaN,1165196264,3.506667
22136,s3073,tv show,tokyo magnitude 8.0,NaN,NaN,japan,NaN,2009,tv-14,1 season,"anime, drama, international",the devastation is unleashed in the span of se...,hs3073,hulu,NaN,NaN,835889856,3.600462

In [19]:
#GUARDO LOS ARCHIVOS
dfFinal.to_csv(r'DATOS/dfFinal.csv')
dfUnido1.to_csv(r'DATOS/DFFINAL_PARA_CONSULTAS.csv')